sudo: required
dist: trusty

language: node_js
node_js: 8

# notifications:
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/593f9ec49210b8694911
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  
install:
  - git clone https://github.com/kevinresol/haxeui-unit
  - cd haxeui-unit
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  - sed -i '/-cp/c\-cp $TRAVIS_BUILD_DIR' haxe_libraries/haxeui-core.hxml # TODO: this should be a lix command
  # - lix install 'gh:haxeui/haxeui-html5#new-component-method'
  
script:
  - lix run travix js -lib haxeui-html5
